// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinApi.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Coins", b =>
                {
                    b.Property<int>("MonedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("MonedaId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            MonedaId = 1,
                            Descripcion = "Bitcoin",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
                            Valor = 23000.0
                        },
                        new
                        {
                            MonedaId = 2,
                            Descripcion = "Ethereum",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
                            Valor = 1247.75
                        },
                        new
                        {
                            MonedaId = 3,
                            Descripcion = "Tether",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/825.png",
                            Valor = 1.0
                        },
                        new
                        {
                            MonedaId = 4,
                            Descripcion = "Binance Coin",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/4687.png",
                            Valor = 239.56
                        },
                        new
                        {
                            MonedaId = 5,
                            Descripcion = "Cardano Coin",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/2010.png",
                            Valor = 27.32
                        },
                        new
                        {
                            MonedaId = 6,
                            Descripcion = "LiteCoin",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/2.png",
                            Valor = 59.229999999999997
                        },
                        new
                        {
                            MonedaId = 7,
                            Descripcion = "Stellar",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/512.png",
                            Valor = 0.127494
                        },
                        new
                        {
                            MonedaId = 8,
                            Descripcion = "DogeCoin",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/74.png",
                            Valor = 0.069000000000000006
                        },
                        new
                        {
                            MonedaId = 9,
                            Descripcion = "XRP",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/52.png",
                            Valor = 0.36105100000000001
                        },
                        new
                        {
                            MonedaId = 10,
                            Descripcion = "BNB",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
                            Valor = 239.59999999999999
                        },
                        new
                        {
                            MonedaId = 11,
                            Descripcion = "TRON",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png",
                            Valor = 0.065000000000000002
                        },
                        new
                        {
                            MonedaId = 12,
                            Descripcion = "Uniswap",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png",
                            Valor = 5.3399999999999999
                        },
                        new
                        {
                            MonedaId = 13,
                            Descripcion = "Cronos",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/3635.png",
                            Valor = 2723.5999999999999
                        },
                        new
                        {
                            MonedaId = 14,
                            Descripcion = "Algorand",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/4030.png",
                            Valor = 0.341862
                        },
                        new
                        {
                            MonedaId = 15,
                            Descripcion = "Aave",
                            ImageUrl = "https://s2.coinmarketcap.com/static/img/coins/64x64/7278.png",
                            Valor = 67.140000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
